[package]
name = "rust-fzf-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
crossterm = "0.27"
ratatui = "0.23"
regex = "1.11.1"
color = "0.2.3"
